---
version: '3'
networks:
  mynet:
    external: true
services:
  db:
    image: mariadb
    networks:
      - mynet
    container_name: db
    hostname: db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${ENCRYPTED_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${ENCRYPTED_PASSWORD}
      TZ: ${TZ}
    ports:
      - "3306:3306"
    volumes:
      - ${DOCKER_DATA}/mariadb/database:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    hostname: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    depends_on:
      - db
    networks:
      - mynet
    ports:
      - "8081:80"
  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    restart: always
    networks:
      - mynet
    ports:
      - "8080:8080"